[main]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\ao\0\0\x4\x3\0\0\0\0\0\0\0\0\0\0\x3\xb1\0\0\x1\xfb\0\0\0\0\x2\0\0\0\a\x80\0\0\0\0\0\0\0\0\0\0\ao\0\0\x4\x3)
windowState=@ByteArray(\0\0\0\xff\0\0\0\0\xfd\0\0\0\0\0\0\ap\0\0\x3\xdb\0\0\0\x4\0\0\0\x4\0\0\0\b\0\0\0\b\xfc\0\0\0\0)

[notification]
app=true
show_msg=true
show_name=true
show_photo=true
sound=true

[onboarding]
initial_setup_completed=true

[performance]
js_memory_limit_index=0
js_memory_limit_mb=0

[permissions]
auto_grant\camera=false
auto_grant\camera_microphone=false
auto_grant\microphone=false
auto_grant\screen_contents=false
auto_grant\screen_contents_audio=false

[system]
confirm_on_close=false
display_backend=auto
download_path=/home/gskumar/Downloads
interface_language=system
notificationCounter=true
quit_in_close=true
spellCheckLanguage=en_IN
spellCheckLanguages=@Variant(\0\0\0\t\0\0\0\x1\0\0\0\n\0\0\0\n\0\x65\0n\0_\0I\0N)
spellCheckProvisionedLocale=en_IN
spellCheckers=true
start_background=false
start_system=false
tray_icon=false
wayland=false

[website]
open_page=false
