-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "Bibata-Modern-Ice")
hl.env("XCURSOR_SIZE", "30")
hl.env("HYPRCURSOR_THEME", "Bibata-Modern-Ice")
hl.env("HYPRCURSOR_SIZE", "30")

-- Settings
hl.config({
    animations = {
        enabled = true,
    },
    decoration = {
        active_opacity = 1.0,
        blur = {
            enabled = false,
        },
        inactive_opacity = 0.9,
        shadow = {
            enabled = false,
        },
    },
    dwindle = {
        force_split = 2,
    },
    general = {
        border_size = 3,
        gaps_in = 3,
        gaps_out = 5,
    },
    input = {
        natural_scroll = true,
        numlock_by_default = true,
        repeat_delay = 500,
        repeat_rate = 40,
        sensitivity = 0.5,
        touchpad = {
            natural_scroll = true,
            scroll_factor = 1.2,
        },
    },
    misc = {
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
    },
})

-- Animations
hl.animation({
    leaf = "workspaces",
    enabled = false,
})
